"""
citation-constellation/app/HOW_TO_RUN.py
=======================================
Information about how to run this tool
"""

HOW_TO_RUN = """


**How to Run Here & Install Locally**

## 1. Using the Web App

This interface runs on SciLifeLab Serve and requires no installation.

**To run a new analysis:**

Click the "🔍 Run Analysis" tab.

1.  **Enter a researcher identifier** in the input field:
    *   An ORCID (e.g., `0000-0000-0000-0000`)
    *   An OpenAlex ID (e.g., `A0000000000`)
    *   You may paste the full URL (e.g., `https://orcid.org/...`) — the tool extracts the ID automatically.
2.  *(Optional)* **Set a career start year** to exclude older publications. This helps resolve name collisions if OpenAlex has merged profiles of researchers with similar names.
3.  *(Optional)* **Adjust the co-author graph depth** (default: 2). Depth 1 includes only direct co-authors; Depth 2 includes co-authors of co-authors; Depth 3 extends one hop further.
4.  *(Optional)* **Enable "Wait for my validation"** to review and confirm potentially misattributed papers flagged by ORCID validation before they are excluded.
5.  *(Optional)* **Upload a custom HEROCON weights JSON** file to override the default classification weights.
6.  Click **"Run Analysis"**.

The tool will fetch data from OpenAlex and process it through Phases 1–3. For a typical researcher with 50–100 publications, this takes 1–4 minutes. Results display BARON and HEROCON scores, interactive visualizations, and a downloadable JSON audit report.

**Rate limit:** 10 analyses per hour per session.

**To visualize existing results:** Click the **"📊 View Existing Audits"** tab to upload a previously downloaded JSON audit report. You can visualize your own past results or audit files shared by colleagues without waiting for computation. Upload one file for full visualization, or **as many files as you want** for side-by-side comparison.

---

## 2. Installing the CLI

For command-line use or batch processing, install the tool locally.

**Installation:**

```bash
git clone https://github.com/citation-cosmograph/citation-constellation.git
cd citation-constellation
pip install -r requirements.txt
```

**Running an analysis:**

Run the full Phase 3 pipeline (includes self-citation, co-author network, and affiliation matching):

```bash
# Using ORCID
python phase3.py --orcid 0000-0000-0000-0000

# Using OpenAlex ID
python phase3.py --openalex-id A0000000000
```

**Common options:**

```bash
--since 2010               # Exclude works published before 2010
--depth 1|2|3              # Co-author graph depth (default: 2)
--export results.json      # Export summary to a specific JSON file
--confirm                  # Interactive review of flagged papers before scoring
--no-audit                 # Skip audit file generation (not recommended)
```

**Output:**
*   Scores and breakdowns print to the console.
*   A timestamped JSON audit file saves to the `./audits/` directory by default.

**Visualizing CLI results:** Audit files generated by the CLI can be uploaded to the web interface (hosted or local) using the **"📊 View Existing Audits"** tab for interactive visualization, charts, and comparison with other researchers.

---

## 3. Installing the Web App Locally

You can run this Gradio interface on your own machine. The local web interface provides the same two-tab experience as the hosted version: run new analyses in the **"🔍 Run Analysis"** tab, or upload existing audit JSON files in the **"📊 View Existing Audits"** tab for visualization without computation.

### Option A: Run with Python (simplest)

If you have Python 3.11+ installed, simply run the Gradio app directly:

```bash
cd citation-constellation/
pip install -r app/requirements.txt
python app/main.py
```

Open your browser to `http://localhost:7860`. You will see both the analysis and visualization tabs available immediately.

### Option B: Build Docker image from source

```bash
cd citation-constellation

# Build the image
docker build --platform linux/amd64 -t citation-constellation:v0.3 .

# Run the container
docker run --rm -it -p 7860:7860 citation-constellation:v0.3
```

Open your browser to `http://localhost:7860`. The **"📊 View Existing Audits"** tab is available for uploading previously saved JSON reports.

### Option C: Use the prebuilt image

Pull and run the prebuilt image from Docker Hub:

```bash
# Pull the image
docker pull mahbub1969/citation-constellation:v1

# Run the container
docker run --rm -it -p 7860:7860 mahbub1969/citation-constellation:v1
```

Open your browser to `http://localhost:7860`. Use the **"📊 View Existing Audits"** tab to load and visualize audit files from your local filesystem.

**Requirements:**
*   For Option A: Python 3.11+, pip
*   For Options B & C: Docker Desktop or Docker Engine, port 7860 available on your host machine
"""
