"""
citation-constellation/app/tabs/visualize.py
=============================================
Tab 2: Upload and visualize existing BARON/HEROCON audit JSON files.
Single file → full visualization. Multiple files → comparison view.
"""

import json
import gradio as gr

from app.branding import DISCLAIMER_SHORT
from app.components.coauthor_graph import build_coauthor_graph
from app.components.trajectory_chart import (
    build_trajectory_chart, 
    build_baron_comparison_trajectory, 
    build_herocon_comparison_trajectory
)
from app.components.score_panel import build_score_donut, format_score_summary
from app.components.classification_table import build_classification_dataframe, build_classification_summary
from app.components.comparison import build_comparison_table, parse_multiple_reports


# ── Strict Schema Definition ──
EXPECTED_SCHEMA = {
    "_meta": {
        "tool": None, "version": None, "phase": None, "identifier": None, 
        "created_at": None, "started_at": None, "completed_at": None, 
        "description": None, "disclaimer": None, 
        "summary": {
            "total_works_analyzed": None, "total_citing_works": None, 
            "total_citations_classified": None, "classification_counts": None, 
            "classification_percentages": None
        }
    },
    "researcher": {
        "openalex_id": None, "orcid": None, "display_name": None, 
        "works_count": None, "cited_by_count": None, "openalex_url": None
    },
    "score": {
        "phase": None, "baron_score": None, "herocon_score": None, 
        "herocon_weights": None, "breakdown": None, "top_self_cited_works": None, 
        "herocon_explanation": None, "coauthor_stats": None
    },
    "ingestion": {
        "works_fetched": None, "citing_works_fetched": None, "citation_links": None, 
        "institutions_fetched": None, "reference_coverage": None, "api_calls": None, 
        "time_elapsed": None, "affiliation_stats": None
    },
    "works": None,
    "citations": None,
    "classifications": None,
    "coauthor_graph": {
        "config": None, "summary": None, "nodes": None, "edges": None
    },
    "affiliation_data": {
        "target_affiliation_history": None, "target_institutions": None, 
        "timeline_stats": None, "hierarchy_stats": None
    },
    "orcid_validation": {
        "orcid": None, "mode": None, "since_year": None, "orcid_works_count": None, 
        "openalex_works_count": None, "verified_count": None, "unverified_count": None, 
        "flagged_count": None, "since_excluded_count": None, "works_used_for_scoring": None, 
        "coverage_pct": None, "orcid_completeness": None, "span_warning": None, 
        "flagged_works": None, "since_excluded_works": None, "match_log": None
    },
    "trajectory": None
}

def validate_schema(data, schema, path="root"):
    """Recursively check that `data` strictly matches the keys in `schema`."""
    if not isinstance(data, dict):
        return f"Expected dictionary object at '{path}', got {type(data).__name__}."
    
    data_keys = set(data.keys())
    schema_keys = set(schema.keys())
    
    # Make 'orcid_validation' optional at the root
    if path == "root" and "orcid_validation" not in data_keys:
        schema_keys.discard("orcid_validation")
    
    # Check for ANY extra or missing keys
    if data_keys != schema_keys:
        extra = data_keys - schema_keys
        missing = schema_keys - data_keys
        err = "Invalid file. Please upload an exact, unmodified JSON report generated by Citation-Constellation."
        if extra: err += f"\nUnexpected keys: {extra}."
        if missing: err += f"\nMissing keys: {missing}."
        return err
        
    # Recursively check sub-dictionaries
    for key, sub_schema in schema.items():
        if key not in data_keys:
            continue  # Skip optional key if it isn't in data
        if isinstance(sub_schema, dict):
            err = validate_schema(data[key], sub_schema, f"{path}.{key}")
            if err: return err
    return None


def build_tab():
    """Build and return the 'Visualize Existing Reports' tab components."""

    with gr.Column():
        gr.Markdown(
            "### Upload Audit Reports\n\n"
            "Upload one or more BARON/HEROCON audit JSON files.\n"
            "- **Single file**: Full visualization with co-author graph, trajectory, and breakdown.\n"
            "- **Multiple files**: Side-by-side comparison table and overlaid trajectories.\n\n"
            "*Accepted format: JSON audit reports generated by citation-constellation (max 100 MB per file).*"
        )

        file_upload = gr.File(
            label="Upload JSON Audit Report(s)",
            file_count="multiple",
            file_types=[".json"],
            type="filepath",
        )

        visualize_btn = gr.Button("📊 Visualize", variant="primary")

        # ── Status / Error ──
        status_output = gr.Markdown(visible=False)

        # ── Single report view ──
        single_section = gr.Column(visible=False)
        with single_section:
            gr.Markdown(f"---\n### *{DISCLAIMER_SHORT}*\n---")
            single_summary = gr.Markdown()
            with gr.Row():
                single_donut = gr.Plot(label="Classification Breakdown")
            single_summary_table = gr.Dataframe(label="Classification Summary", interactive=False)
            single_graph = gr.Plot(label="Co-Author Network")
            single_trajectory = gr.Plot(label="Career Trajectory")
            with gr.Accordion("All Citation Classifications", open=False):
                single_full_table = gr.Dataframe(label="Citations", interactive=False)

        # ── Multi-report comparison view ──
        multi_section = gr.Column(visible=False)
        with multi_section:
            gr.Markdown(f"---\n### *{DISCLAIMER_SHORT}*\n---")
            gr.Markdown("### Researcher Comparison")
            comparison_table = gr.Dataframe(label="Score Comparison", interactive=False)
            
            # --- Two comparison plots ---
            #with gr.Row():
            comparison_trajectory_baron = gr.Plot(label="BARON Trajectory Comparison")
            comparison_trajectory_herocon = gr.Plot(label="HEROCON Trajectory Comparison")
            

            gr.Markdown("### Individual Reports")
            # Increased from 5 to 115 to handle more comparisons
            individual_accordions = []
            for i in range(115):
                with gr.Accordion(f"Researcher {i+1}", open=False, visible=False) as acc:
                    ind_summary = gr.Markdown()
                    ind_donut = gr.Plot()
                    ind_graph = gr.Plot()
                    ind_trajectory = gr.Plot()
                    individual_accordions.append({
                        "accordion": acc,
                        "summary": ind_summary,
                        "donut": ind_donut,
                        "graph": ind_graph,
                        "trajectory": ind_trajectory,
                    })

        # ── Event handler ──
        def on_visualize(files):
            if not files:
                return {
                    status_output: gr.update(value="⚠️ Please upload at least one JSON file.", visible=True),
                    single_section: gr.update(visible=False),
                    multi_section: gr.update(visible=False),
                }

            # Read, parse, and strictly validate files
            contents = []
            file_errors = []

            for f in files:
                filepath = f if isinstance(f, str) else f.name
                
                if not filepath.lower().endswith(".json"):
                    file_errors.append(f"'{filepath}' is not a JSON file.")
                    continue

                try:
                    with open(filepath, "r", encoding="utf-8") as fh:
                        raw_content = fh.read()
                        
                        try:
                            data = json.loads(raw_content)
                        except json.JSONDecodeError:
                            file_errors.append(f"'{filepath}' contains invalid or corrupted JSON.")
                            continue
                        
                        schema_error = validate_schema(data, EXPECTED_SCHEMA)
                        if schema_error:
                            file_errors.append(f"Error in '{filepath}': {schema_error}")
                            continue

                        contents.append(raw_content)
                except Exception as e:
                    file_errors.append(f"Error reading file '{filepath}': {e}")
                    continue

            # If ALL files failed, return the errors immediately
            if not contents:
                error_msg = "❌ " + "\n\n❌ ".join(file_errors)
                return {
                    status_output: gr.update(value=error_msg, visible=True),
                    single_section: gr.update(visible=False),
                    multi_section: gr.update(visible=False),
                }

            # Proceed with valid files
            reports, parse_errors = parse_multiple_reports(contents)
            
            all_errors = file_errors + (parse_errors if parse_errors else [])
            
            if not reports:
                error_msg = "❌ " + "\n\n❌ ".join(all_errors)
                return {
                    status_output: gr.update(value=error_msg, visible=True),
                    single_section: gr.update(visible=False),
                    multi_section: gr.update(visible=False),
                }

            warning = ""
            if all_errors:
                warning = "⚠️ **Some files had issues and were skipped:**\n- " + "\n- ".join(all_errors) + "\n\n"

            # ── Single file ──
            if len(reports) == 1:
                audit = reports[0]
                updates = {
                    status_output: gr.update(value=warning if warning else "", visible=bool(warning)),
                    single_section: gr.update(visible=True),
                    multi_section: gr.update(visible=False),
                    single_summary: format_score_summary(audit),
                    single_donut: build_score_donut(audit),
                    single_summary_table: build_classification_summary(audit),
                    single_graph: build_coauthor_graph(audit),
                    single_trajectory: build_trajectory_chart(audit),
                    single_full_table: build_classification_dataframe(audit),
                }
                return updates

            # ── Multiple files ──
            updates = {
                status_output: gr.update(
                    value=warning + f"Loaded {len(reports)} reports for comparison.",
                    visible=True,
                ),
                single_section: gr.update(visible=False),
                multi_section: gr.update(visible=True),
                comparison_table: build_comparison_table(reports),
                # --- NEW: Call both functions ---
                comparison_trajectory_baron: build_baron_comparison_trajectory(reports),
                comparison_trajectory_herocon: build_herocon_comparison_trajectory(reports),
            }

            # Fill individual accordions (up to 115)
            for i, acc_data in enumerate(individual_accordions):
                if i < len(reports):
                    r = reports[i]
                    name = r.get("researcher", {}).get("display_name", f"Researcher {i+1}")
                    updates[acc_data["accordion"]] = gr.update(label=name, visible=True, open=False)
                    updates[acc_data["summary"]] = format_score_summary(r)
                    updates[acc_data["donut"]] = build_score_donut(r)
                    updates[acc_data["graph"]] = build_coauthor_graph(r)
                    updates[acc_data["trajectory"]] = build_trajectory_chart(r)
                else:
                    updates[acc_data["accordion"]] = gr.update(visible=False)

            return updates

        # Collect all outputs
        all_outputs = [
            status_output, single_section, multi_section,
            single_summary, single_donut, single_summary_table,
            single_graph, single_trajectory, single_full_table,
            comparison_table, comparison_trajectory_baron, comparison_trajectory_herocon,
        ]
        for acc_data in individual_accordions:
            all_outputs.extend([
                acc_data["accordion"], acc_data["summary"],
                acc_data["donut"], acc_data["graph"], acc_data["trajectory"],
            ])

        visualize_btn.click(
            fn=on_visualize,
            inputs=[file_upload],
            outputs=all_outputs,
        )